### ISSUE TITLE
Subject: Inquiry About Replicating Results from "RNTrajRec: Road Network Enhanced Trajectory Recovery with Spatial-Temporal Transformer"

### ISSUE THREAD

**Issue by zhaoyaya1234** [chenyuqi990215/RNTrajRec#11]
Dear Author,

I hope this message finds you well. I am writing to you regarding your paper, "RNTrajRec: Road Network Enhanced Trajectory Recovery with Spatial-Temporal Transformer." I have been diligently working to replicate the experimental results from your study, specifically those conducted on the Porto dataset.

Due to limited GPU resources on our university servers, I am unable to run experiments over a large area. Consequently, I confined the experimental region to coordinates [41.121621, -8.644531, 41.167815, -8.596830], encompassing a total of 4,800 road segments. I utilized the code available at the following link: [https://drive.google.com/file/d/1docCbgLCZzkH4KwkQzI4XtvO-8a-qykW/view?usp=drive_link](https://drive.google.com/file/d/1docCbgLCZzkH4KwkQzI4XtvO-8a-qykW/view?usp=drive_link).

However, I encountered a discrepancy in the results. While my reconstruction accuracy (acc) reached 0.48, I noticed that in your paper - or in similar studies like MTrajRec - the accuracy surpasses 0.54. I am curious about what might be contributing to this difference. Could it be a potential oversight in my replication of the code, or might it pertain to the modifications in the dataset parameters?

I genuinely respect your work and am eager to understand it more deeply. Any insights or suggestions you could provide would be immensely appreciated. I am looking forward to your kind response.

Thank you for your time and consideration.

**Comment by chenyuqi990215** [comment]
Maybe the experimental region and the dataset size matter. We provide an open-source dataset in https://drive.google.com/drive/folders/1QNADHYKQNSo574S04iyOjh4LYySSpC2N.

**Comment by zhaoyaya1234** [comment]
I feel very grateful to receive your reply, good luck!
