### ISSUE TITLE
怎么使用这个框架训练自己的数据

### ISSUE THREAD

**Issue by yuangui0316** [chenyuqi990215/RNTrajRec#4]
请问一下如何将地图数据和gps轨迹数据转换成train_input.txt内的格式，还有roadnet的数据也要从新生成吗？谢谢

**Comment by chenyuqi990215** [comment]
您可以参考这个博客来处理数据：[RNTrajRec训练自己的数据](https://blog.csdn.net/m0_37500540/article/details/130625385)。

另外，我们的代码是基于前人工作MtrajRec，您也可以参考[MTrajRec实现](https://github.com/huiminren/MTrajRec)构建自己的数据。
