### ISSUE TITLE
[dataset] Porto datasets

### ISSUE THREAD

**Issue by sxwee** [chenyuqi990215/RNTrajRec#5]
There is limited information available about the Proto datasets. Could you please provide more details about the raw datasets? I am interested in utilizing these public datasets for my work. Thank you in advance for your assistance.

**Comment by chenyuqi990215** [comment]
please refer to issue #4. If you have any other problem, please let me know!

**Comment by sxwee** [comment]
Thank you very much. I have another one question: Is Proto a complete dataset? Could you share the whole dataset if possible?

**Comment by chenyuqi990215** [comment]
The original Porto dataset can be found at [Kaggle Link](https://www.kaggle.com/datasets/crailtap/taxi-trajectory).

For data processing and other open-source datasets, please refer to [tptk](https://github.com/sjruan/tptk) and [MTrajRec](https://github.com/huiminren/MTrajRec).

**Comment by sxwee** [comment]
Thanks for your help! It's the road network of Porto provided by you complete? Can I directly use the road network provided by you for map matching?

**Comment by chenyuqi990215** [comment]
Yes, the road network of Porto is complete. I have uploaded the map matching codes used in the paper under `preprocess` fold.

**Comment by sxwee** [comment]
Could you please show how to use `hmm.py` and `hmm.cpp` for map matching? It looks like` hmm.cpp` is incomplete and has syntax issues.

**Comment by chenyuqi990215** [comment]
```
g++ hmm.cpp -o hmm
```

Feel free to clip the error information here so that I could help you solve the problem.

**Comment by chenyuqi990215** [comment]
You possibly could not directly run `hmm.cpp`, try `hmm.py` instead.

**Comment by sxwee** [comment]
command: `g++ hmm.cpp -o hmm` with following compile error infos:
```
hmm.cpp:23:7: error: expected ‘:’ before ‘double’
   23 | public
      |       ^
      |       :
   24 |     double lon;
      |     ~~~~~~
hmm.cpp: In function ‘void read()’:
hmm.cpp:139:17: warning: format ‘%s’ expects argument of type ‘char*’, but argument 2 has type ‘char (*)[50]’ [-Wformat=]
  139 |         scanf("%s", &way_string);
      |                ~^   ~~~~~~~~~~~
      |                 |   |
      |                 |   char (*)[50]
      |                 char*
hmm.cpp: In function ‘void matching_hmm()’:
hmm.cpp:500:52: error: ‘routeNetworkDistBetweenTwoTrajPoints’ was not declared in this scope; did you mean ‘distBetweenTwoTrajPoints’?
  500 |                                       (long double)routeNetworkDistBetweenTwoTrajPoints) /
      |                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                    distBetweenTwoTrajPoints
hmm.cpp:504:66: error: ‘sp’ was not declared in this scope; did you mean ‘p’?
  504 |                         long double tmpTotalProbForTransaction = sp->score * transactionProb;
      |                                                                  ^~
      |                                                                  p
hmm.cpp:511:66: error: ‘currentMaxProbTmp’ was not declared in this scope; did you mean ‘currentMaxProb’?
  511 |                     emissionProbs[currentCanadidateRoadIndex] *= currentMaxProbTmp;
      |                                                                  ^~~~~~~~~~~~~~~~~
      |                                                                  currentMaxProb
hmm.cpp:513:41: error: ‘p’ was not declared in this scope
  513 |                 scores.push_back(Score(*p, emissionProbs[currentCanadidateRoadIndex], preColumnIndex,
      |                                         ^
hmm.cpp:513:87: error: ‘preColumnIndex’ was not declared in this scope
  513 |                 scores.push_back(Score(*p, emissionProbs[currentCanadidateRoadIndex], preColumnIndex,
      |                                                                                       ^~~~~~~~~~~~~~
hmm.cpp:514:40: error: ‘currentDistfromStart’ was not declared in this scope
  514 |                                        currentDistfromStart));
      |                                        ^~~~~~~~~~~~~~~~~~~~
hmm.cpp:520:22: error: ‘emissionProbs’ was not declared in this scope; did you mean ‘EmissionPro’?
  520 |             delete[] emissionProbs;
      |                      ^~~~~~~~~~~~~
      |                      EmissionPro
hmm.cpp:521:31: error: ‘trajectoryIterator’ was not declared in this scope
  521 |             formerTrajPoint = trajectoryIterator;
      |                               ^~~~~~~~~~~~~~~~~~
hmm.cpp:527:33: error: ‘scores’ was not declared in this scope; did you mean ‘Score’?
  527 |             for (int j = 0; j < scores.size(); ++j) scores[j].score /= currentMaxProb;
      |                                 ^~~~~~
      |                                 Score
hmm.cpp:527:72: error: ‘currentMaxProb’ was not declared in this scope
  527 |             for (int j = 0; j < scores.size(); ++j) scores[j].score /= currentMaxProb;
      |                                                                        ^~~~~~~~~~~~~~
hmm.cpp:528:35: error: ‘scores’ was not declared in this scope; did you mean ‘Score’?
  528 |             scoreMatrix.push_back(scores);
      |                                   ^~~~~~
      |                                   Score
hmm.cpp:539:41: error: ‘scoreMatrix’ was not declared in this scope
  539 |         int startColumnIndex = GetIndex(scoreMatrix.back());
      |                                         ^~~~~~~~~~~
hmm.cpp:544:21: error: ‘i’ was not declared in this scope
  544 |                 ans[i].push_front(temp);
      |                     ^
hmm.cpp:548:21: error: ‘i’ was not declared in this scope
  548 |                 ans[i].push_front(temp);
      |                     ^
hmm.cpp: At global scope:
hmm.cpp:555:1: error: expected declaration before ‘}’ token
  555 | }
      | ^
hmm.cpp:575:6: error: variable or field ‘work’ declared void
  575 | void work(Trajectory t) {
      |      ^~~~
hmm.cpp:575:11: error: ‘Trajectory’ was not declared in this scope
  575 | void work(Trajectory t) {
      |           ^~~~~~~~~~
```

**Comment by chenyuqi990215** [comment]
Please check the latest code, thanks.

**Comment by xinghun0525** [comment]
I would greatly appreciate it if you could provide some clarification on the following points:

1. Interpolation Implementation:
I am curious to know how the interpolation process is implemented within the project. Specifically, could you please explain the approach or algorithm used for interpolation?

2. test_input_8.txt Generation:
In relation to the project's test_input_8.txt file, how was this particular input file obtained or generated? It would be helpful to understand the process or data source used to create this specific test input.

3. Order of HMM and Linear Interpolation:
I noticed that the project applies the HMM algorithm first and then performs linear interpolation to obtain map-matched trajectories. I am interested in understanding the reasoning behind this order of operations. What factors influenced the decision to apply HMM before the linear interpolation process?

Thank you very much for your time and attention to my inquiries.

**Comment by chenyuqi990215** [comment]
@xinghun0525 I have replied to your problems on #6.

**Comment by sxwee** [comment]
Thanks a million! I noticed that the raw Porto dataset contains more than one million trajectories, while in your paper, you used around 150,000 trajectories. I would like to know how you selected this subset. Did you randomly select the trajectories or was there a specific selection criteria in place?

**Comment by chenyuqi990215** [comment]
We almost randomly select the samples. To make sure that these trajectories are neither too long nor too short, we first filter out trajectories that are too short, i.e. shorter than 600 seconds, or too long, i.e. longer than 1200 seconds. If more trajectories are founded, we randomly sample 150, 000 trajectories.

**Comment by chenyuqi990215** [comment]
I will close this issue right now, if you have other questions, fell free to reopen it.
