### ISSUE TITLE
[Data Preprocessing] Questions about the data preprocessing procedure.

### ISSUE THREAD

**Issue by chenyuqi990215** [chenyuqi990215/RNTrajRec#6]
I would greatly appreciate it if you could provide some clarification on the following points:

1. Interpolation Implementation:
I am curious to know how the interpolation process is implemented within the project. Specifically, could you please explain the approach or algorithm used for interpolation?

2. test_input_8.txt Generation:
In relation to the project's test_input_8.txt file, how was this particular input file obtained or generated? It would be helpful to understand the process or data source used to create this specific test input.

3. Order of HMM and Linear Interpolation:
I noticed that the project applies the HMM algorithm first and then performs linear interpolation to obtain map-matched trajectories. I am interested in understanding the reasoning behind this order of operations. What factors influenced the decision to apply HMM before the linear interpolation process?

Thank you very much for your time and attention to my inquiries.

_Originally posted by @xinghun0525 in https://github.com/chenyuqi990215/RNTrajRec/issues/5#issuecomment-1596394672_

**Comment by chenyuqi990215** [comment]
As for the first problem, the linear interpolation algorithm is implemented in `preprocess/interpolate_trajectory.py` Line 30-58. The key idea is the following: assuming that x and y are two GPS points and r is the interpolate ratio. Assume that r equals to 2/3, then on Euclidean space, the result should be x + (2 / 3) (y - x) = (x + 2*y) / 3. For Earth distance space, we solve the problem by calculating the geo-center of [x, y, y], which is similar to (x + 2*y) / 3.

**Comment by chenyuqi990215** [comment]
As for the second problem, we apologize for not providing a detailed illustration of the preprocessing procedure in our paper.
To generate the training data, first, we obtain raw GPS trajectories that are irregularly sampled, we denote these trajectories as `A`.  Next, we perform linear interpolation on `A` using `interpolate_trajectory.py` to obtain regularly sampled raw GPS trajectories as `B`.  Also, we perform map_matching on `A` using `hmm.py` to obtain irregularly sampled map-matched trajectories as `C`. Next,  we perform interpolation on `C` to obtain map-matched epsilon-sampled trajectory via `epsilon_trajectory.py`, which performs linear interpolation on the road network, we denote the output as `D`.  Finally, we perform the downsampling process on `B` to obtain the input, and `D` as the training target.

**Comment by chenyuqi990215** [comment]
As for the third problem, during the preprocess, we first use HMM to obtain the corresponding road segment, followed by linear interpolation to obtain a regularly sampled trajectory. We believe that since the sample rate of the raw GPS is high enough, therefore, changing the order of HMM and interpolation will not lead to great changes.

**Comment by xinghun0525** [comment]
Many thanks for taking the time to address my concerns and provide a satisfactory resolution!

**Comment by sxwee** [comment]
I followed your processing procedure to handle the Porto dataset, but when I ran it on RNTrajRec, I encountered a KeyError. It seems that the road segments corresponding to the trajectory points obtained using HMM are not within the specified area of the Porto road network. Have you encountered this situation before? How should I handle this?
Error Info:
```
    mm_eids.append([self.rn.valid_edge_one[candi_pt.eid]])  # keep the same format as seq
KeyError: 8988
```

**Comment by sxwee** [comment]
I have followed your data preprocessing procedure as outlined below:

```
raw GPS trajectories(A)
A---------interpolate_trajectory.py-------->B
A---------hmm.py---------project_trajectory.py--------->C---------epsilon_trajectory.py--------->D
B as input, D as output
```

However, I have noticed that there is a significant difference in the GPS coordinates between the trajectory points in `B` and `D`. Is this considered normal?
![diff](https://github.com/chenyuqi990215/RNTrajRec/assets/49050326/c54357f8-25f0-42bf-bdc3-162c9e578459)
